---
title: "Untitled"
author: "Caitie"
date: "30/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
library(parallel)
```


This script combines the watershed data with the state tract data to determine the population per watershed.


```{r}
shed<-"WBDHU8"
watersheds_proj<-st_read(here(paste0("raw_data/WBD_", shed, ".shp")))
state_files<-list.files(path = here("raw_data/State_tract_files"), pattern = "_Tract_Population.shp", full.names = T)

```


```{r}

ws_state_combo<-function(i){
  print(i)
  name<-substr(i, start = 70,stop =71) #you will need to adjust this based on the number of letters in the filename i
  d<-st_read(i)
  d_proj<-st_transform(d, crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m no_defs")
  d_proj$area<-st_area(d_proj)
  e<-extent(d_proj)
  crop_watersheds<-st_crop(watersheds_proj, e)
  water_state<-st_intersection(d_proj, crop_watersheds)
  water_state$ws_area<-st_area(water_state)
  water_state$prop_area<-water_state$ws_area/water_state$area
  water_state$final_pop_age<-water_state$Population*water_state$prop_area

test<- water_state %>% 
  as.data.frame() %>% 
  group_by(huc8, Pop_group) %>% 
  summarise(Pop_ws_age_true = sum(final_pop_age)) %>% 
  mutate(Pop_ws_age = as.numeric(Pop_ws_age_true))

 fwrite(test, here(paste0("output_data/State_tract_files/", name, "_Pop_group_watershed_",shed,".csv")))

}

mclapply(state_files, ws_state_combo, mc.cores = 2)
```
