---
title: "Watershed_boundaries"
author: "Caitie"
date: "30/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rgdal)
library(rgeos)
library(sf)
library(ggplot2)
library(raster)
library(rasterVis)
library(maptools)
library(tidycensus)
library(tidyverse)
library(parallel)
library(data.table)
library(here)
library(nhdplusTools)
```

# Load watershed data

U.S. watershed data is available at: https://www.usgs.gov/core-science-systems/ngp/national-hydrography/watershed-boundary-dataset?qt-science_support_page_related_con=4#qt-science_support_page_related_con

```{r}
outdir<-here("raw_data")

download_wbd(
  outdir,
  url = paste0("https://prd-tnm.s3.amazonaws.com/StagedProducts/",
    "Hydrography/WBD/National/GDB/WBD_National_GDB.zip"),
  progress = TRUE
)

fgdb<-here("raw_data/WBD_National_GDB.gdb")

fc_list<-ogrListLayers(fgdb)

```

## Pick watershed

We use hydrological unit 8 - but this can be easily changed (e.g., change argument to WBDHU4, etc.) The higher the value the finer the detail of watersheds
```{r}
shed<-"WBDHU8"
```

## Watershed Boundary Data

```{r}
watersheds<-st_read(dsn = fgdb, layer = shed)

#Albers equal area conic
#ESRI:102003

watersheds_proj<-st_transform(watersheds, crs = "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m no_defs")

```

```{r}
# Make geometry valid and calculate area per watershed
watersheds_proj<-st_make_valid(watersheds_proj)
watersheds_proj$area<-st_area(watersheds_proj)
st_crs(watersheds_proj)<-"+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m no_defs"

st_write(watersheds_proj, here(paste0("raw_data/WBD_", shed, ".shp")), append = F)
```
